<?php
$pizzaSql = 
"SELECT 
	PZ.NAME PIZZERIA,
	PZ.CITY CITY,
	P.NAME \"PIZZA NAME\",
	P.STYLE STYLE,
	SR.NAME SAUCE, 
	DR.NAME DOUGH, 
	CT.NAME \"CRUST THICKNESS\", 
	CR.NAME CHEESE, 
	AR.NAME AUTHENTICITY, 
	OVR.NAME OVERALL_RATING
FROM 
	PIZZERIA PZ, 
	PIZZA P, 
	PIZZA_QUALITY PQ, 
	THICKNESS_RATING CT, 
	QUALITY_RATING SR, 
	QUALITY_RATING DR, 
	QUALITY_RATING CR, 
	QUALITY_RATING AR, 
	QUALITY_RATING OVR

WHERE PZ.ID = PQ.PIZZERIA_ID
    AND P.ID = PQ.PIZZA_ID
    AND PQ.SAUCE_RATING = SR.ID
    AND PQ.DOUGH_RATING = DR.ID
    AND PQ.CRUST_THICKNESS = CT.ID
    AND PQ.CHEESE_RATING = CR.ID
    AND PQ.AUTHENTICITY = AR.ID
    AND PQ.OVERALL = OVR.ID
ORDER BY OVR.ID DESC, PZ.NAME";

$qualityRatingSql = "SELECT * FROM QUALITY_RATING ORDER BY ID DESC";

$crustRatingSql = "SELECT * FROM THICKNESS_RATING ORDER BY ID";

$pizzeriaSql = "SELECT ID, NAME FROM PIZZERIA";

$recommendedSql = 
"SELECT
  PZ.NAME,
  PZ.CITY
FROM PIZZERIA PZ
WHERE PZ.ID NOT IN
  (SELECT
    PA.PIZZERIA_ID
  FROM PIZZA PA
    LEFT OUTER JOIN PIZZERIA PZ ON PA.PIZZERIA_ID = PZ.ID)";

/*
"SELECT PZ.NAME PIZZERIA, PZ.CITY 
FROM PIZZERIA PZ,
    (SELECT MAX(PIZZERIA_ID) MAX_ID FROM PIZZA)PID_CHECK
WHERE PZ.ID > PID_CHECK.MAX_ID";
*/
?>
